name: animated_calendar
description: "A beautiful, animated calendar package for Flutter with a blue-and-white theme."
version: 1.0.0
repository: https://github.com/kavindumal/animated_calendar
homepage: https://kavindusportfolio.web.app/
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
